#!/bin/bash

# Output "device discovery" information on stdout:
if [ "$#" = "0" ]; then
    echo 'direct lego-printer "Joseph Lego Printer" "Joseph Lego Printer"'
    exit 0
else
    # Standard args passed by CUPS
    id=$1
    user=$2
    title=$3
    copies=$4
    opt=$5
    file=$6
    current=`date "+%Y-%m-%d %H:%M:%S"`
    ip=${DEVICE_URI:14}


    echo "----------[$current]----------" >> /tmp/lego-printer.log
    echo "Printing ..." >> /tmp/lego-printer.log
    echo "uri    = $DEVICE_URI" >> /tmp/lego-printer.log
    echo "ip     = $ip" >> /tmp/lego-printer.log
    echo "id     = $id" >> /tmp/lego-printer.log
    echo "user   = $user" >> /tmp/lego-printer.log
    echo "title  = $title" >> /tmp/lego-printer.log
    echo "copies = $copies" >> /tmp/lego-printer.log
    echo "opt    = $opt" >> /tmp/lego-printer.log
    echo "file   = $file" >> /tmp/lego-printer.log


    # work in a temp directory
    tmp=$( mktemp -d -t lego-printer-XXXXXXXX )
    cd $tmp

    # Redirect the piped postscript to a file
    cat - > print.ps

    # ImageMagik the postscript to png.

    convert print.ps print.png >> /tmp/lego-printer.log
    convert -resize 250x340 print.png out.png >> /tmp/lego-printer.log
    convert out.png -background white -alpha remove out1.png  >> /tmp/lego-printer.log
    convert -monochrome out1.png print.png >> /tmp/lego-printer.log

    /opt/JosephLegoPrinter/Driver.php ${ip} ${tmp}/print.png >> /tmp/lego-printer.log

    current=`date "+%Y-%m-%d %H:%M:%S"`
    echo "----------[$current]----------" >> /tmp/lego-printer.log

    exit 0
fi

